[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
halo_escrow = "3dPU7bDe3Bqfzx7z2g4hVr9cNQGeZqR1oHCkti5uD3bJ"

[programs.localnet]
halo_escrow = "3dPU7bDe3Bqfzx7z2g4hVr9cNQGeZqR1oHCkti5uD3bJ"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[hooks]
